version: "3.1"
services:
  api:
    build: 
      dockerfile: ./api-server/Dockerfile
    ports: 
      - "8080:8080"
  web:
    build: 
      dockerfile: ./client/Dockerfile
    command: sh -c "yarn dev"
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
  # grpc-server:
  #   command: sh grpc-server/scripts/server.sh
  #   build:
  #     dockerfile: ./grpc-server/Dockerfile
  #   volumes:
  #     - ./grpc-server:/go/src/grpc--server
  #   ports:
  #     - "9090:9090"
  #   depends_on:
  #     - proto
  # proto:
  #   command: sh proto/scripts/protoc.sh
  #   build:
  #     dockerfile: ./proto/Dockerfile
  #   volumes:
  #     - .:/proto