version: "3.1"
services:
  api:
    build: 
      dockerfile: ./api-server/dockerfile
    ports: 
      - "8080:8080"
    # networks:
    #   ecs-network:
    #     ipv4_address: 172.30.0.3
  web:
    build: 
      dockerfile: ./client/dockerfile
    command: sh -c "yarn dev"
    ports:
      - "3000:3000"
  proto:
    command: sh proto/scripts/protoc.sh
    build:
      dockerfile: ./proto/dockerfile
    volumes:
      - .:/proto