version: "3.1"
services:
  api:
    build: ./api-server
    ports: 
      - "8080:8080"
  web:
    build: ./client
    command: sh -c "yarn dev"
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
  mysql:
    build: ./mysql   
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d  #初期データをマウントする場所
    image: giganoto-sql # イメージの名前
    environment:
      - MYSQL_ROOT_PASSWORD=admin  #コンテナ内のMySQLを起動する際のパスワードを設定
  # grpc-server:
  #   command: sh grpc-server/scripts/server.sh
  #   build:
  #     dockerfile: ./grpc-server/Dockerfile
  #   volumes:
  #     - ./grpc-server:/go/src/grpc--server
  #   ports:
  #     - "9090:9090"
  #   depends_on:
  #     - proto
  # proto:
  #   command: sh proto/scripts/protoc.sh
  #   build:
  #     dockerfile: ./proto/Dockerfile
  #   volumes:
  #     - .:/proto