version: "3.1"
services:
  api:
    build: 
      dockerfile: ./api-server/Dockerfile
    ports: 
      - "8080:8080"
  web:
    build: 
      dockerfile: ./client/Dockerfile
    command: sh -c "yarn dev"
    ports:
      - "3000:3000"
  proto:
    command: sh proto/scripts/protoc.sh
    build:
      dockerfile: ./proto/Dockerfile
    volumes:
      - .:/proto