FROM golang:1.17 

WORKDIR /go/src
COPY ./api-server /go/src/

ENV CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

COPY . .
RUN go mod tidy

RUN go build -o bin/app ./server.go

CMD ["go", "run", "server.go"]
